api: # Name
  Version: 1
  ProxyService:
  IPs:
    tasks.api: tasks.api # Docker Swarm
    api: api # Docker
    192.168.1.10: 127.0.0.1 # local development
  Port: 1234
  Hosts:
    - localhost
    - 127.0.0.1
    - lvh.me
    - api.lvh.me
  Basepath: "{{.Name}}/v{{.Version}}"
  Data:
    sometext: "something in staging"
    somenumber: 33

frontend: # Name
  Version: 1.0.39
  IPs:
    tasks.frontend: tasks.frontend
  Hosts:
    - example.com
    - www.example.com
    - example.co
